# Generated by Django 5.2.3 on 2025-06-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_rename_user_cerimonialista_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('cerimonialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cerimonialista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('fornecedores', models.ManyToManyField(blank=True, to='usuario.fornecedor')),
            ],
        ),
    ]
