# Generated by Django 5.2.3 on 2025-06-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerimonialista',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='empresa',
            new_name='nome_empresa',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('BUFFET', 'Buffet / Gastronomia'), ('DECORACAO', 'Decoração'), ('SOM_ILUMINACAO', 'Som e Iluminação'), ('FOTOGRAFIA', 'Fotografia'), ('FILMAGEM', 'Filmagem / Vídeo'), ('BOLO_DOCES', 'Bolo e Doces'), ('MUSICA', 'Música / Banda / DJ'), ('TRANSPORTE', 'Transporte / Limousine'), ('VESTUARIO', 'Vestuário / Noivos e Convidados'), ('BELEZA', 'Beleza / Maquiagem e Cabelo'), ('CONVITES', 'Convites e Papelaria'), ('ALUGUEL_MOVEIS', 'Aluguel de Móveis e Estruturas'), ('ENTRETERIMENTO', 'Entretenimento / Shows'), ('SEGURANCA', 'Segurança'), ('OUTROS', 'Outros Serviços')], default='OUTROS', max_length=50),
        ),
    ]
