# Generated by Django 5.2.3 on 2025-06-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_user_cerimonialista_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='cerimonialista',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='cerimonialista',
            name='cpf_cnpj',
            field=models.CharField(default='00000000000000', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='cerimonialista',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='00000000000000', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(default='00000000000000', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
