# Generated by Django 5.2.3 on 2025-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_user_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default='teste@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='senha',
            field=models.CharField(default='senha123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default=986757181, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('buffet', 'Buffet'), ('decoracao', 'Decoração'), ('som_iluminacao', 'Som e Iluminação'), ('fotografia', 'Fotografia'), ('video', 'Filmagem / Vídeo'), ('bolo_doces', 'Bolo e Doces'), ('musica', 'Música / Banda / DJ'), ('transporte', 'Transporte / Limousine'), ('vestuario', 'Vestuário / Noivos e Convidados'), ('beleza', 'Beleza / Maquiagem e Cabelo'), ('convites', 'Convites e Papelaria'), ('aluguel_moveis', 'Aluguel de Móveis e Estruturas'), ('entretenimento', 'Entretenimento / Shows'), ('seguranca', 'Segurança'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
