# Generated by Django 5.2.3 on 2025-06-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Receber', 'Receber'), ('Pagar', 'Pagar')], max_length=10)),
                ('valor_total', models.FloatField()),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('casamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamentos.casamento')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.financeiro')),
            ],
        ),
    ]
