# Generated by Django 5.1.7 on 2025-06-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casamentos', '0001_initial'),
        ('cerimonialista', '0001_initial'),
        ('cliente', '0001_initial'),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateField()),
                ('status', models.CharField(choices=[('Assinado', 'Assinado'), ('Pendente', 'Pendente')], max_length=20)),
                ('casamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamentos.casamento')),
                ('cerimonialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerimonialista.cerimonialista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
            ],
        ),
    ]
