# Generated by Django 5.2.3 on 2025-06-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casamentos', '0001_initial'),
        ('usuario', '0003_rename_user_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateField()),
                ('status', models.CharField(choices=[('Assinado', 'Assinado'), ('Pendente', 'Pendente')], max_length=20)),
                ('casamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamentos.casamento')),
                ('cerimonialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cerimonialista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.fornecedor')),
            ],
        ),
    ]
